# Generated by Django 3.2.7 on 2022-12-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userbankaccount_visa_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='master_card_number',
            field=models.CharField(blank=True, default=4916414504095223, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='virtual_card_number',
            field=models.CharField(blank=True, default=4556745492741673, max_length=225, null=True),
        ),
    ]
