# Generated by Django 3.2.7 on 2022-12-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20221230_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankaccount',
            name='master_card_number',
            field=models.CharField(blank=True, default=5561484943388989, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='virtual_card_number',
            field=models.CharField(blank=True, default=4929892218032480, max_length=225, null=True),
        ),
    ]
