# Generated by Django 3.2.7 on 2022-12-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20221230_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='profiles'),
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='master_card_number',
            field=models.CharField(blank=True, default=5161719623743373, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='virtual_card_number',
            field=models.CharField(blank=True, default=4539001347408460, max_length=225, null=True),
        ),
    ]
