# Generated by Django 3.2.7 on 2023-06-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20221230_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankaccount',
            name='master_card_number',
            field=models.CharField(blank=True, default=5389940556514914, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='virtual_card_number',
            field=models.CharField(blank=True, default=4485705419667571, max_length=225, null=True),
        ),
    ]
