# Generated by Django 3.2.7 on 2023-06-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20230628_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='savings_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='master_card_number',
            field=models.CharField(blank=True, default=5380948728850842, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='virtual_card_number',
            field=models.CharField(blank=True, default=4716683938697778, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='visa_card_number',
            field=models.CharField(blank=True, default=4556675101194305, max_length=225, null=True),
        ),
    ]
