# Generated by Django 3.2.7 on 2023-12-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20230629_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='addtess_2',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='master_card_number',
            field=models.CharField(blank=True, default=5334881855304597, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='virtual_card_number',
            field=models.CharField(blank=True, default=4716900272844265, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='visa_card_number',
            field=models.CharField(blank=True, default=4024007129339452, max_length=225, null=True),
        ),
    ]
