# Generated by Django 3.2.7 on 2023-12-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20231212_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankaccount',
            name='birth_date',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='master_card_number',
            field=models.CharField(blank=True, default=5377626612010559, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='virtual_card_number',
            field=models.CharField(blank=True, default=4916881293995732, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='visa_card_number',
            field=models.CharField(blank=True, default=4929539741056649, max_length=225, null=True),
        ),
    ]
