# Generated by Django 4.0.4 on 2022-12-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='routing_number',
            field=models.IntegerField(default=0),
        ),
    ]
