# Generated by Django 4.0.4 on 2022-12-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
