# Generated by Django 3.2.7 on 2022-12-30 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20221230_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_id',
            new_name='transaction_id_field',
        ),
    ]
