# Generated by Django 3.2.7 on 2022-12-30 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_rename_transaction_id_transaction_transaction_id_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_id_field',
            new_name='id',
        ),
    ]
